apiVersion: v1
kind: Namespace
metadata:
  name: ss-sample-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-sample-app
  namespace: ss-sample-app
  labels:
      app: ss-sample-app
  template:
    metadata:
      labels:
        app: ss-sample-app
    spec:
      containers:
      - name: sample-app
        image: lander2k2/server-side-sample-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: "SAMPLE_API_URL"
          value: "https://forward-proxy.forward-proxy-system.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: ss-sample-app
  namespace: ss-sample-app
spec:
  selector:
    app: ss-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

